apiVersion: v1
kind: ReplicationController
metadata:
  name: nsx-demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nsx-demo
        secgroup: web-tier
    spec:
      containers:
      - name: nsx-demo
        image: harbor.corp.local/1935/nsx-demo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nsx-demo
  labels:
    app: mod2
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: nsx-demo
  selector:
    app: nsx-demo
  type: LoadBalancer
